main:stack.o check.o path.o main.c
	gcc stack.o path.o check.o main.c -o main
stack.o:stack.c
	gcc -c stack.c -o stack.o
check.o:check.c
	gcc -c check.c -o check.o
path.o:path.c
	gcc -c path.c -o path.o